#!/bin/csh
#SBATCH -N 1
#SBATCH -t 2:00:00
#SBATCH -p pbatch

/g/g90/hkhetaw/TraceR/TraceR/bin/traceR --sync=1 -- /g/g90/hkhetaw/TraceR/TraceR/EXPERIMENTS/fattree-4-lassen-gd.conf tracer_config_256 >> 4_lassen_gd_256.out 
