#!/bin/csh
#SBATCH -N 1
#SBATCH -t 5:00:00
#SBATCH -p pbatch

/g/g90/hkhetaw/TraceR/TraceR/bin/traceR --sync=1 -- /g/g90/hkhetaw/TraceR/TraceR/EXPERIMENTS/fattree-6-lassen-gd.conf tracer_config_128 >> 6_lassen_gd_128.out 
